import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { Separator } from '@/components/ui/separator'
import NavBar from '@/components/NavBar'
import { dark } from '@clerk/themes'
import { ThemeProvider } from '@/providers/ThemeProvider'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ClerkProvider appearance={dark}>
			<html lang='en' className={cn(inter.className)}>
				<body>
					<ThemeProvider>
						<div className='flex min-h-screen w-full flex-col items-center bg-neutral-50 dark:bg-black'>
							<NavBar />
							<Separator className='' />
							<main className='flex flex-grow w-full justify-center bg-white dark:bg-neutral-950'>
								{children}
							</main>
						</div>
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	)
}
