import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { Separator } from '@/components/ui/separator'
import NavBar from '@/components/NavBar'
import { dark } from '@clerk/themes'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ClerkProvider appearance={dark}>
			<html lang='en'>
				<body className={inter.className}>
					<div className='flex min-h-screen w-full flex-col items-center bg-neutral-800'>
						<NavBar />
						<Separator className='opacity-0' />
						{children}
					</div>
				</body>
			</html>
		</ClerkProvider>
	)
}
